class_name EventBusService
extends Node

@warning_ignore("unused_signal")
signal game_paused(paused: bool)
@warning_ignore("unused_signal")
signal scene_change_requested(scene_path: String)
@warning_ignore("unused_signal")
signal scene_changed(scene_path: String)
@warning_ignore("unused_signal")
signal save_requested(slot: String)
@warning_ignore("unused_signal")
signal game_saved(slot: String)
@warning_ignore("unused_signal")
signal game_loaded(slot: String, data: Dictionary)
@warning_ignore("unused_signal")
signal item_collected(item: ItemData, amount: int)
@warning_ignore("unused_signal")
signal inventory_changed(owner: Node)
@warning_ignore("unused_signal")
signal dialogue_started(dialogue: DialogueData)
@warning_ignore("unused_signal")
signal dialogue_finished(dialogue: DialogueData)
@warning_ignore("unused_signal")
signal quest_started(quest_id: String)
@warning_ignore("unused_signal")
signal quest_completed(quest_id: String)
